services:
  fgg-db:
    build:
      context: ../fgg-database
    container_name: fgg-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  fgg:
    container_name: fgg-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - fgg-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_LOGINS: ${ADMIN_LOGINS}
    volumes:
      - ./logs:/app/logs
