openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.9.0
paths:
  /games/{login}/wishlist:
    get:
      operationId: getUserWishlistGames
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/WishlistGamesResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/all/wishlist:
    get:
      operationId: getAllWishlistGames
      tags:
        - Games
      responses:
        '200':
          $ref: '#/components/responses/WishlistGamesByLoginsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/{login}/current:
    get:
      operationId: getUserCurrentGame
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/CurrentGameResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/all/current:
    get:
      operationId: getAllCurrentGame
      tags:
        - Games
      responses:
        '200':
          $ref: '#/components/responses/CurrentGameByLoginsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/self/current/roll:
    post:
      operationId: rollNewCurrentGame
      tags:
        - Games
      responses:
        '200':
          $ref: '#/components/responses/CurrentGameResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/self/current/finish:
    post:
      operationId: finishOwnCurrentGame
      tags:
        - Games
      responses:
        '204':
          description: Success.
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/self/current/cancel:
    post:
      operationId: cancelOwnCurrentGame
      tags:
        - Games
      responses:
        '204':
          description: Success.
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/{login}/history:
    get:
      operationId: getUserGameHistory
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/CurrentGamesResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/all/history:
    get:
      operationId: getAllGameHistory
      tags:
        - Games
      responses:
        '200':
          $ref: '#/components/responses/CurrentGamesByLoginsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    Login:
      type: string
      pattern: ^\w+$
      minLength: 3
      maxLength: 35
    Name:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 70
    WishlistGame:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
      required:
        - name
    WishlistGames:
      type: array
      items:
        $ref: '#/components/schemas/WishlistGame'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    WishlistGamesByLogin:
      type: object
      properties:
        login:
          $ref: '#/components/schemas/Login'
        wishlistGames:
          $ref: '#/components/schemas/WishlistGames'
      required:
        - login
        - wishlistGames
    WishlistGamesByLogins:
      type: array
      items:
        $ref: '#/components/schemas/WishlistGamesByLogin'
    Duration:
      type: string
      format: duration
      example: PT2h10m5s
      description: The duration notation as defined by ISO 8601
    CurrentGame:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        state:
          type: string
          enum:
            - started
            - finished
            - cancelled
        timeSpent:
          $ref: '#/components/schemas/Duration'
        finishDate:
          type: string
          format: date-time
      required:
        - name
        - state
        - timeSpent
    CurrentGameByLogin:
      type: object
      properties:
        login:
          $ref: '#/components/schemas/Login'
        currentGame:
          $ref: '#/components/schemas/CurrentGame'
      required:
        - login
        - currentGame
    CurrentGameByLogins:
      type: array
      items:
        $ref: '#/components/schemas/CurrentGameByLogin'
    CurrentGames:
      type: array
      items:
        $ref: '#/components/schemas/CurrentGame'
    CurrentGamesByLogin:
      type: object
      properties:
        login:
          $ref: '#/components/schemas/Login'
        currentGames:
          $ref: '#/components/schemas/CurrentGames'
      required:
        - login
        - currentGames
    CurrentGamesByLogins:
      type: array
      items:
        $ref: '#/components/schemas/CurrentGamesByLogin'
  parameters:
    Login:
      name: login
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Login'
  responses:
    WishlistGamesResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WishlistGames'
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    WishlistGamesByLoginsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WishlistGamesByLogins'
    CurrentGameResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CurrentGame'
    CurrentGameByLoginsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CurrentGameByLogins'
    CurrentGamesResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CurrentGames'
    CurrentGamesByLoginsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CurrentGamesByLogins'
