openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.10.0
paths:
  /wheel-effects/{login}/history:
    get:
      operationId: getUserWheelEffectHistory
      tags:
        - WheelEffects
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/RolledWheelEffectsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available:
    get:
      operationId: getAvailableWheelEffects
      tags:
        - WheelEffects
      responses:
        '200':
          $ref: '#/components/responses/WheelEffectsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll:
    post:
      operationId: rollAvailableWheelEffects
      tags:
        - WheelEffects
      responses:
        '200':
          $ref: '#/components/responses/RolledWheelEffectsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll/count:
    get:
      operationId: getAvailableWheelEffectRollsCount
      tags:
        - WheelEffects
      responses:
        '200':
          $ref: '#/components/responses/PointsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll/apply:
    post:
      operationId: applyAvailableWheelEffectRoll
      tags:
        - WheelEffects
      requestBody:
        $ref: '#/components/requestBodies/PointChangeByLoginsRequest'
      responses:
        '200':
          $ref: '#/components/responses/FreePointChangeResultByLoginsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    Login:
      type: string
      pattern: ^\w+$
      minLength: 3
      maxLength: 35
    Name:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 70
    WheelEffect:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        description:
          type: string
      required:
        - name
    RolledWheelEffect:
      allOf:
        - $ref: '#/components/schemas/WheelEffect'
        - type: object
          properties:
            position:
              type: integer
              format: int
            rollDate:
              type: string
              format: date-time
          required:
            - rollDate
    RolledWheelEffects:
      type: array
      items:
        $ref: '#/components/schemas/RolledWheelEffect'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    WheelEffects:
      type: array
      items:
        $ref: '#/components/schemas/WheelEffect'
    Points:
      type: integer
      format: int
      minimum: 0
    PointChange:
      type: object
      properties:
        changeSource:
          type: string
        desiredChangeValue:
          type: integer
          format: int
    PointChangeByLogins:
      type: array
      items:
        type: object
        properties:
          login:
            $ref: '#/components/schemas/Login'
          pointChange:
            $ref: '#/components/schemas/PointChange'
        required:
          - login
          - pointChange
    PointChangeResult:
      allOf:
        - $ref: '#/components/schemas/PointChange'
        - type: object
          properties:
            actualChangeValue:
              type: integer
              format: int
            finalValue:
              $ref: '#/components/schemas/Points'
            changeDate:
              type: string
              format: date-time
          required:
            - actualChangeValue
            - finalValue
            - changeDate
    FreePointChangeResult:
      allOf:
        - $ref: '#/components/schemas/PointChangeResult'
        - type: object
          properties:
            changeSource:
              enum:
                - own-wheel-effect
                - other-wheel-effect
                - quest
                - base-teleport
                - sandstorm
                - other
            wheelEffectName:
              $ref: '#/components/schemas/Name'
    FreePointChangeResultByLogins:
      type: array
      items:
        type: object
        properties:
          login:
            $ref: '#/components/schemas/Login'
          changeResult:
            $ref: '#/components/schemas/FreePointChangeResult'
        required:
          - login
          - changeResult
  parameters:
    Login:
      name: login
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Login'
  responses:
    RolledWheelEffectsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RolledWheelEffects'
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    WheelEffectsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WheelEffects'
    PointsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Points'
    FreePointChangeResultByLoginsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FreePointChangeResultByLogins'
  requestBodies:
    PointChangeByLoginsRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PointChangeByLogins'
