openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.13.0
paths:
  /wheel-effects/{login}/history:
    get:
      operationId: getUserWheelEffectHistory
      tags:
        - WheelEffects
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/RolledWheelEffectHistoriesResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available:
    get:
      operationId: getAvailableWheelEffects
      tags:
        - WheelEffects
      responses:
        '200':
          $ref: '#/components/responses/WheelEffectsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll:
    post:
      operationId: rollAvailableWheelEffects
      tags:
        - WheelEffects
      requestBody:
        $ref: '#/components/requestBodies/WheelEffectRollRequest'
      responses:
        '200':
          $ref: '#/components/responses/RolledWheelEffectsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll/count:
    get:
      operationId: getAvailableWheelEffectRollsCount
      tags:
        - WheelEffects
      responses:
        '200':
          $ref: '#/components/responses/PointsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll/last:
    get:
      operationId: getLastRolledWheelEffects
      tags:
        - WheelEffects
      responses:
        '200':
          $ref: '#/components/responses/RolledWheelEffectsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll/last/clear:
    post:
      operationId: clearLastRolledWheelEffects
      tags:
        - WheelEffects
      responses:
        '204':
          description: Success.
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll/apply:
    post:
      operationId: applyAvailableWheelEffectRoll
      tags:
        - WheelEffects
      requestBody:
        $ref: '#/components/requestBodies/WheelEffectRollApplyRequest'
      responses:
        '200':
          $ref: '#/components/responses/PointChangeResultByLoginsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    Login:
      type: string
      pattern: ^\w+$
      minLength: 3
      maxLength: 35
    Name:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 70
    WheelEffect:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        description:
          type: string
      required:
        - name
    RolledWheelEffectHistory:
      allOf:
        - $ref: '#/components/schemas/WheelEffect'
        - type: object
          properties:
            rollDate:
              type: string
              format: date-time
          required:
            - rollDate
    RolledWheelEffectHistories:
      type: array
      items:
        $ref: '#/components/schemas/RolledWheelEffectHistory'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    WheelEffects:
      type: array
      items:
        $ref: '#/components/schemas/WheelEffect'
    WheelEffectRoll:
      type: object
      properties:
        isReroll:
          type: boolean
          default: false
    RolledWheelEffect:
      allOf:
        - $ref: '#/components/schemas/WheelEffect'
        - type: object
          properties:
            position:
              type: integer
              format: int
            rollDate:
              type: string
              format: date-time
            isApplied:
              type: boolean
          required:
            - position
            - rollDate
            - isApplied
    RolledWheelEffects:
      type: array
      items:
        $ref: '#/components/schemas/RolledWheelEffect'
    Points:
      type: integer
      format: int
      minimum: 0
    PointChange:
      type: object
      properties:
        changeSource:
          type: string
        desiredChangeValue:
          type: integer
          format: int
      required:
        - changeSource
        - desiredChangeValue
    PointChangeByLogins:
      type: array
      items:
        type: object
        properties:
          login:
            $ref: '#/components/schemas/Login'
          freePointChange:
            $ref: '#/components/schemas/PointChange'
          availableRollChange:
            $ref: '#/components/schemas/PointChange'
        required:
          - login
          - freePointChange
    WheelEffectRollApply:
      type: object
      properties:
        wheelEffectName:
          $ref: '#/components/schemas/Name'
        pointChanges:
          $ref: '#/components/schemas/PointChangeByLogins'
      required:
        - wheelEffectName
        - pointChanges
    PointChangeResult:
      type: object
      properties:
        actualChangeValue:
          type: integer
          format: int
        finalValue:
          $ref: '#/components/schemas/Points'
      required:
        - actualChangeValue
        - finalValue
    PointChangeResultByTypes:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/PointChangeResult'
    PointChangeResultByLogins:
      type: array
      items:
        type: object
        properties:
          login:
            $ref: '#/components/schemas/Login'
          changeResults:
            $ref: '#/components/schemas/PointChangeResultByTypes'
        required:
          - login
          - changeResults
  parameters:
    Login:
      name: login
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Login'
  responses:
    RolledWheelEffectHistoriesResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RolledWheelEffectHistories'
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    WheelEffectsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WheelEffects'
    RolledWheelEffectsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RolledWheelEffects'
    PointsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Points'
    PointChangeResultByLoginsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PointChangeResultByLogins'
  requestBodies:
    WheelEffectRollRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WheelEffectRoll'
    WheelEffectRollApplyRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WheelEffectRollApply'
