openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.9.0
paths:
  /auth/signup:
    $ref: "../paths/auth/signup.yaml"

  /auth/login:
    $ref: "../paths/auth/login.yaml"

  /auth/logout:
    $ref: "../paths/auth/logout.yaml"
  
