openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.9.0
paths:
  /games/{login}/wishlist:
    $ref: "../paths/games/login/wishlist.yaml"

  /games/all/wishlist:
    $ref: "../paths/games/all/wishlist.yaml"

  /games/{login}/current:
    $ref: "../paths/games/login/current.yaml"

  /games/all/current:
    $ref: "../paths/games/all/current.yaml"

  /games/self/current/roll:
    $ref: "../paths/games/self/current/roll.yaml"

  /games/self/current/finish:
    $ref: "../paths/games/self/current/finish.yaml"

  /games/self/current/cancel:
    $ref: "../paths/games/self/current/cancel.yaml"

  /games/{login}/history:
    $ref: "../paths/games/login/history.yaml"

  /games/all/history:
    $ref: "../paths/games/all/history.yaml"
  
