openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.10.0
paths:
  /points/{login}/info:
    $ref: "../paths/points/login/info.yaml"

  /points/all/info:
    $ref: "../paths/points/all/info.yaml"

  /points/{login}/territory-points:
    $ref: "../paths/points/login/territory-points.yaml"

  /points/{login}/territory-points/history:
    $ref: "../paths/points/login/territory-points/history.yaml"

  /points/free-points:
    $ref: "../paths/points/free-points.yaml"

  /points/{login}/free-points/history:
    $ref: "../paths/points/login/free-points/history.yaml"

  /points/experience-points:
    $ref: "../paths/points/experience-points.yaml"

  /points/territory-hours:
    $ref: "../paths/points/territory-hours.yaml"