openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.9.0
paths:
  /timers/self/current:
    $ref: "../paths/timers/self/current.yaml"

  /timers/self/current/start:
    $ref: "../paths/timers/self/current/start.yaml"

  /timers/self/current/pause:
    $ref: "../paths/timers/self/current/pause.yaml"
