openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.10.0
paths:
  /timers/current:
    $ref: "../paths/timers/current.yaml"

  /timers/current/start:
    $ref: "../paths/timers/current/start.yaml"

  /timers/current/pause:
    $ref: "../paths/timers/current/pause.yaml"
