openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.10.0
paths:
  /users/all/names:
    $ref: "../paths/users/all/names.yaml"

  /users/display-name:
    $ref: "../paths/users/display-name.yaml"