// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// Defines values for ConflictErrorCode.
const (
	CURRENTGAMEALREADYEXISTS ConflictErrorCode = "CURRENT_GAME_ALREADY_EXISTS"
	EMAILALREADYEXISTS       ConflictErrorCode = "EMAIL_ALREADY_EXISTS"
	NOAVAILABLEROLLS         ConflictErrorCode = "NO_AVAILABLE_ROLLS"
	NOCOMPLETEDTIMERS        ConflictErrorCode = "NO_COMPLETED_TIMERS"
	NOUNPLAYEDGAMES          ConflictErrorCode = "NO_UNPLAYED_GAMES"
	TIMERINCORRECTSTATE      ConflictErrorCode = "TIMER_INCORRECT_STATE"
	USERNAMEALREADYEXISTS    ConflictErrorCode = "USERNAME_ALREADY_EXISTS"
)

// Defines values for GameState.
const (
	GameStateCancelled GameState = "cancelled"
	GameStateFinished  GameState = "finished"
	GameStateStarted   GameState = "started"
)

// Defines values for InternalServerErrorCode.
const (
	UNEXPECTED InternalServerErrorCode = "UNEXPECTED"
)

// Defines values for NotAuthorizedErrorCode.
const (
	NOACTIVESESSION NotAuthorizedErrorCode = "NO_ACTIVE_SESSION"
	WRONGAUTHDATA   NotAuthorizedErrorCode = "WRONG_AUTH_DATA"
)

// Defines values for NotFoundErrorCode.
const (
	GAMENOTFOUND  NotFoundErrorCode = "GAME_NOT_FOUND"
	TIMERNOTFOUND NotFoundErrorCode = "TIMER_NOT_FOUND"
	USERNOTFOUND  NotFoundErrorCode = "USER_NOT_FOUND"
)

// Defines values for TimerState.
const (
	TimerStateCreated  TimerState = "created"
	TimerStateFinished TimerState = "finished"
	TimerStatePaused   TimerState = "paused"
	TimerStateRunning  TimerState = "running"
)

// Defines values for TimerActionType.
const (
	Pause TimerActionType = "pause"
	Start TimerActionType = "start"
	Stop  TimerActionType = "stop"
)

// AvailableEffect defines model for AvailableEffect.
type AvailableEffect struct {
	Description *string `json:"description,omitempty"`
	Name        Name    `json:"name"`
}

// ConflictError defines model for ConflictError.
type ConflictError struct {
	Code    ConflictErrorCode `json:"code"`
	Message string            `json:"message"`
}

// ConflictErrorCode defines model for ConflictError.Code.
type ConflictErrorCode string

// Effect defines model for Effect.
type Effect struct {
	CreateDate  time.Time  `json:"createDate"`
	Description *string    `json:"description,omitempty"`
	GameName    *Name      `json:"gameName,omitempty"`
	Name        *Name      `json:"name,omitempty"`
	RollDate    *time.Time `json:"rollDate,omitempty"`
}

// Effects defines model for Effects.
type Effects = []Effect

// Email defines model for Email.
type Email = string

// Game defines model for Game.
type Game struct {
	FinishDate *time.Time `json:"finishDate,omitempty"`
	HourCount  int        `json:"hourCount"`
	Link       *string    `json:"link,omitempty"`
	Name       Name       `json:"name"`
	State      GameState  `json:"state"`
}

// GameState defines model for Game.State.
type GameState string

// Games defines model for Games.
type Games = []Game

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Code    InternalServerErrorCode `json:"code"`
	Message string                  `json:"message"`
}

// InternalServerErrorCode defines model for InternalServerError.Code.
type InternalServerErrorCode string

// Name defines model for Name.
type Name = string

// NotAuthorizedError defines model for NotAuthorizedError.
type NotAuthorizedError struct {
	Code    NotAuthorizedErrorCode `json:"code"`
	Message string                 `json:"message"`
}

// NotAuthorizedErrorCode defines model for NotAuthorizedError.Code.
type NotAuthorizedErrorCode string

// NotFoundError defines model for NotFoundError.
type NotFoundError struct {
	Code    NotFoundErrorCode `json:"code"`
	Message string            `json:"message"`
}

// NotFoundErrorCode defines model for NotFoundError.Code.
type NotFoundErrorCode string

// Password defines model for Password.
type Password = string

// Timer defines model for Timer.
type Timer struct {
	DurationInS      int        `json:"durationInS"`
	RemainingTimeInS int        `json:"remainingTimeInS"`
	State            TimerState `json:"state"`
	TimerActionDate  *time.Time `json:"timerActionDate,omitempty"`
}

// TimerState defines model for Timer.State.
type TimerState string

// TimerAction defines model for TimerAction.
type TimerAction struct {
	RemainingTimeInS int             `json:"remainingTimeInS"`
	Type             TimerActionType `json:"type"`
}

// TimerActionType defines model for TimerAction.Type.
type TimerActionType string

// UnplayedGame defines model for UnplayedGame.
type UnplayedGame struct {
	Link *string `json:"link,omitempty"`
	Name Name    `json:"name"`
}

// UnplayedGames defines model for UnplayedGames.
type UnplayedGames = []UnplayedGame

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Name     Name     `json:"name"`
	Password Password `json:"password"`
}

// SignUpJSONBody defines parameters for SignUp.
type SignUpJSONBody struct {
	Email    Email    `json:"email"`
	Name     Name     `json:"name"`
	Password Password `json:"password"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody SignUpJSONBody

// AddUnplayedGamesJSONRequestBody defines body for AddUnplayedGames for application/json ContentType.
type AddUnplayedGamesJSONRequestBody = UnplayedGames

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in an existing user
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// Log out the current user
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// Register a new user account
	// (POST /auth/signup)
	SignUp(ctx echo.Context) error
	// Get a list of effects available for rolling
	// (POST /effects/available)
	GetAvailableEffects(ctx echo.Context) error
	// Check if there are any effect rolls available
	// (GET /effects/has-roll)
	CheckAvailableEffectRoll(ctx echo.Context) error
	// Get a list of all effect rolls
	// (GET /effects/history)
	GetEffectHistory(ctx echo.Context) error
	// Make the roll of the effect available
	// (POST /effects/roll)
	MakeEffectRoll(ctx echo.Context) error
	// Get the current game
	// (GET /games/current)
	GetCurrentGame(ctx echo.Context) error
	// Cancel the current game
	// (POST /games/current/cancel)
	CancelCurrentGame(ctx echo.Context) error
	// Complete the current game
	// (POST /games/current/finish)
	FinishCurrentGame(ctx echo.Context) error
	// Get a list of all games played
	// (GET /games/history)
	GetGameHistory(ctx echo.Context) error
	// Select a random game from the wishlist
	// (POST /games/roll)
	MakeGameRoll(ctx echo.Context) error
	// Get game wishlist
	// (GET /games/unplayed)
	GetUnplayedGames(ctx echo.Context) error
	// Add game wishlist
	// (POST /games/unplayed)
	AddUnplayedGames(ctx echo.Context) error
	// Get a timer for the current game
	// (GET /timers/current)
	GetCurrentTimer(ctx echo.Context) error
	// Pause the current timer
	// (POST /timers/current/pause)
	PauseCurrentTimer(ctx echo.Context) error
	// Start or continue the current timer
	// (POST /timers/current/start)
	StartCurrentTimer(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// SignUp converts echo context to params.
func (w *ServerInterfaceWrapper) SignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignUp(ctx)
	return err
}

// GetAvailableEffects converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvailableEffects(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvailableEffects(ctx)
	return err
}

// CheckAvailableEffectRoll converts echo context to params.
func (w *ServerInterfaceWrapper) CheckAvailableEffectRoll(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CheckAvailableEffectRoll(ctx)
	return err
}

// GetEffectHistory converts echo context to params.
func (w *ServerInterfaceWrapper) GetEffectHistory(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEffectHistory(ctx)
	return err
}

// MakeEffectRoll converts echo context to params.
func (w *ServerInterfaceWrapper) MakeEffectRoll(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.MakeEffectRoll(ctx)
	return err
}

// GetCurrentGame converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentGame(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentGame(ctx)
	return err
}

// CancelCurrentGame converts echo context to params.
func (w *ServerInterfaceWrapper) CancelCurrentGame(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CancelCurrentGame(ctx)
	return err
}

// FinishCurrentGame converts echo context to params.
func (w *ServerInterfaceWrapper) FinishCurrentGame(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FinishCurrentGame(ctx)
	return err
}

// GetGameHistory converts echo context to params.
func (w *ServerInterfaceWrapper) GetGameHistory(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGameHistory(ctx)
	return err
}

// MakeGameRoll converts echo context to params.
func (w *ServerInterfaceWrapper) MakeGameRoll(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.MakeGameRoll(ctx)
	return err
}

// GetUnplayedGames converts echo context to params.
func (w *ServerInterfaceWrapper) GetUnplayedGames(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUnplayedGames(ctx)
	return err
}

// AddUnplayedGames converts echo context to params.
func (w *ServerInterfaceWrapper) AddUnplayedGames(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddUnplayedGames(ctx)
	return err
}

// GetCurrentTimer converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentTimer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentTimer(ctx)
	return err
}

// PauseCurrentTimer converts echo context to params.
func (w *ServerInterfaceWrapper) PauseCurrentTimer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PauseCurrentTimer(ctx)
	return err
}

// StartCurrentTimer converts echo context to params.
func (w *ServerInterfaceWrapper) StartCurrentTimer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StartCurrentTimer(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/auth/login", wrapper.Login)
	router.POST(baseURL+"/auth/logout", wrapper.Logout)
	router.POST(baseURL+"/auth/signup", wrapper.SignUp)
	router.POST(baseURL+"/effects/available", wrapper.GetAvailableEffects)
	router.GET(baseURL+"/effects/has-roll", wrapper.CheckAvailableEffectRoll)
	router.GET(baseURL+"/effects/history", wrapper.GetEffectHistory)
	router.POST(baseURL+"/effects/roll", wrapper.MakeEffectRoll)
	router.GET(baseURL+"/games/current", wrapper.GetCurrentGame)
	router.POST(baseURL+"/games/current/cancel", wrapper.CancelCurrentGame)
	router.POST(baseURL+"/games/current/finish", wrapper.FinishCurrentGame)
	router.GET(baseURL+"/games/history", wrapper.GetGameHistory)
	router.POST(baseURL+"/games/roll", wrapper.MakeGameRoll)
	router.GET(baseURL+"/games/unplayed", wrapper.GetUnplayedGames)
	router.POST(baseURL+"/games/unplayed", wrapper.AddUnplayedGames)
	router.GET(baseURL+"/timers/current", wrapper.GetCurrentTimer)
	router.POST(baseURL+"/timers/current/pause", wrapper.PauseCurrentTimer)
	router.POST(baseURL+"/timers/current/start", wrapper.StartCurrentTimer)

}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200Response struct {
}

func (response Login200Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Login401JSONResponse NotAuthorizedError

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login500JSONResponse InternalServerError

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200Response struct {
}

func (response Logout200Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Logout401JSONResponse NotAuthorizedError

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Logout500JSONResponse InternalServerError

func (response Logout500JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SignUpRequestObject struct {
	Body *SignUpJSONRequestBody
}

type SignUpResponseObject interface {
	VisitSignUpResponse(w http.ResponseWriter) error
}

type SignUp200Response struct {
}

func (response SignUp200Response) VisitSignUpResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type SignUp401JSONResponse NotAuthorizedError

func (response SignUp401JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SignUp409JSONResponse ConflictError

func (response SignUp409JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type SignUp500JSONResponse InternalServerError

func (response SignUp500JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAvailableEffectsRequestObject struct {
}

type GetAvailableEffectsResponseObject interface {
	VisitGetAvailableEffectsResponse(w http.ResponseWriter) error
}

type GetAvailableEffects200JSONResponse AvailableEffect

func (response GetAvailableEffects200JSONResponse) VisitGetAvailableEffectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAvailableEffects401JSONResponse NotAuthorizedError

func (response GetAvailableEffects401JSONResponse) VisitGetAvailableEffectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAvailableEffects404JSONResponse ConflictError

func (response GetAvailableEffects404JSONResponse) VisitGetAvailableEffectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAvailableEffects500JSONResponse InternalServerError

func (response GetAvailableEffects500JSONResponse) VisitGetAvailableEffectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CheckAvailableEffectRollRequestObject struct {
}

type CheckAvailableEffectRollResponseObject interface {
	VisitCheckAvailableEffectRollResponse(w http.ResponseWriter) error
}

type CheckAvailableEffectRoll200JSONResponse bool

func (response CheckAvailableEffectRoll200JSONResponse) VisitCheckAvailableEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CheckAvailableEffectRoll401JSONResponse NotAuthorizedError

func (response CheckAvailableEffectRoll401JSONResponse) VisitCheckAvailableEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CheckAvailableEffectRoll404JSONResponse NotFoundError

func (response CheckAvailableEffectRoll404JSONResponse) VisitCheckAvailableEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CheckAvailableEffectRoll500JSONResponse InternalServerError

func (response CheckAvailableEffectRoll500JSONResponse) VisitCheckAvailableEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetEffectHistoryRequestObject struct {
}

type GetEffectHistoryResponseObject interface {
	VisitGetEffectHistoryResponse(w http.ResponseWriter) error
}

type GetEffectHistory200JSONResponse Effects

func (response GetEffectHistory200JSONResponse) VisitGetEffectHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEffectHistory401JSONResponse NotAuthorizedError

func (response GetEffectHistory401JSONResponse) VisitGetEffectHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetEffectHistory404JSONResponse NotFoundError

func (response GetEffectHistory404JSONResponse) VisitGetEffectHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetEffectHistory500JSONResponse InternalServerError

func (response GetEffectHistory500JSONResponse) VisitGetEffectHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MakeEffectRollRequestObject struct {
}

type MakeEffectRollResponseObject interface {
	VisitMakeEffectRollResponse(w http.ResponseWriter) error
}

type MakeEffectRoll200JSONResponse Effect

func (response MakeEffectRoll200JSONResponse) VisitMakeEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MakeEffectRoll401JSONResponse NotAuthorizedError

func (response MakeEffectRoll401JSONResponse) VisitMakeEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type MakeEffectRoll404JSONResponse NotFoundError

func (response MakeEffectRoll404JSONResponse) VisitMakeEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MakeEffectRoll409JSONResponse ConflictError

func (response MakeEffectRoll409JSONResponse) VisitMakeEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type MakeEffectRoll500JSONResponse InternalServerError

func (response MakeEffectRoll500JSONResponse) VisitMakeEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentGameRequestObject struct {
}

type GetCurrentGameResponseObject interface {
	VisitGetCurrentGameResponse(w http.ResponseWriter) error
}

type GetCurrentGame200JSONResponse Game

func (response GetCurrentGame200JSONResponse) VisitGetCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentGame401JSONResponse NotAuthorizedError

func (response GetCurrentGame401JSONResponse) VisitGetCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentGame404JSONResponse NotFoundError

func (response GetCurrentGame404JSONResponse) VisitGetCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentGame500JSONResponse InternalServerError

func (response GetCurrentGame500JSONResponse) VisitGetCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CancelCurrentGameRequestObject struct {
}

type CancelCurrentGameResponseObject interface {
	VisitCancelCurrentGameResponse(w http.ResponseWriter) error
}

type CancelCurrentGame200Response struct {
}

func (response CancelCurrentGame200Response) VisitCancelCurrentGameResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type CancelCurrentGame401JSONResponse NotAuthorizedError

func (response CancelCurrentGame401JSONResponse) VisitCancelCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CancelCurrentGame404JSONResponse NotFoundError

func (response CancelCurrentGame404JSONResponse) VisitCancelCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CancelCurrentGame500JSONResponse InternalServerError

func (response CancelCurrentGame500JSONResponse) VisitCancelCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type FinishCurrentGameRequestObject struct {
}

type FinishCurrentGameResponseObject interface {
	VisitFinishCurrentGameResponse(w http.ResponseWriter) error
}

type FinishCurrentGame200Response struct {
}

func (response FinishCurrentGame200Response) VisitFinishCurrentGameResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type FinishCurrentGame401JSONResponse NotAuthorizedError

func (response FinishCurrentGame401JSONResponse) VisitFinishCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type FinishCurrentGame404JSONResponse NotFoundError

func (response FinishCurrentGame404JSONResponse) VisitFinishCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type FinishCurrentGame409JSONResponse ConflictError

func (response FinishCurrentGame409JSONResponse) VisitFinishCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type FinishCurrentGame500JSONResponse InternalServerError

func (response FinishCurrentGame500JSONResponse) VisitFinishCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetGameHistoryRequestObject struct {
}

type GetGameHistoryResponseObject interface {
	VisitGetGameHistoryResponse(w http.ResponseWriter) error
}

type GetGameHistory200JSONResponse Games

func (response GetGameHistory200JSONResponse) VisitGetGameHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGameHistory401JSONResponse NotAuthorizedError

func (response GetGameHistory401JSONResponse) VisitGetGameHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetGameHistory404JSONResponse NotFoundError

func (response GetGameHistory404JSONResponse) VisitGetGameHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetGameHistory500JSONResponse InternalServerError

func (response GetGameHistory500JSONResponse) VisitGetGameHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MakeGameRollRequestObject struct {
}

type MakeGameRollResponseObject interface {
	VisitMakeGameRollResponse(w http.ResponseWriter) error
}

type MakeGameRoll200JSONResponse Game

func (response MakeGameRoll200JSONResponse) VisitMakeGameRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MakeGameRoll401JSONResponse NotAuthorizedError

func (response MakeGameRoll401JSONResponse) VisitMakeGameRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type MakeGameRoll404JSONResponse NotFoundError

func (response MakeGameRoll404JSONResponse) VisitMakeGameRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MakeGameRoll409JSONResponse ConflictError

func (response MakeGameRoll409JSONResponse) VisitMakeGameRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type MakeGameRoll500JSONResponse InternalServerError

func (response MakeGameRoll500JSONResponse) VisitMakeGameRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetUnplayedGamesRequestObject struct {
}

type GetUnplayedGamesResponseObject interface {
	VisitGetUnplayedGamesResponse(w http.ResponseWriter) error
}

type GetUnplayedGames200JSONResponse UnplayedGames

func (response GetUnplayedGames200JSONResponse) VisitGetUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUnplayedGames401JSONResponse NotAuthorizedError

func (response GetUnplayedGames401JSONResponse) VisitGetUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUnplayedGames404JSONResponse NotFoundError

func (response GetUnplayedGames404JSONResponse) VisitGetUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetUnplayedGames500JSONResponse InternalServerError

func (response GetUnplayedGames500JSONResponse) VisitGetUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddUnplayedGamesRequestObject struct {
	Body *AddUnplayedGamesJSONRequestBody
}

type AddUnplayedGamesResponseObject interface {
	VisitAddUnplayedGamesResponse(w http.ResponseWriter) error
}

type AddUnplayedGames200Response struct {
}

func (response AddUnplayedGames200Response) VisitAddUnplayedGamesResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type AddUnplayedGames401JSONResponse NotAuthorizedError

func (response AddUnplayedGames401JSONResponse) VisitAddUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AddUnplayedGames404JSONResponse NotFoundError

func (response AddUnplayedGames404JSONResponse) VisitAddUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddUnplayedGames500JSONResponse InternalServerError

func (response AddUnplayedGames500JSONResponse) VisitAddUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentTimerRequestObject struct {
}

type GetCurrentTimerResponseObject interface {
	VisitGetCurrentTimerResponse(w http.ResponseWriter) error
}

type GetCurrentTimer200JSONResponse Timer

func (response GetCurrentTimer200JSONResponse) VisitGetCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentTimer401JSONResponse NotAuthorizedError

func (response GetCurrentTimer401JSONResponse) VisitGetCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentTimer404JSONResponse NotFoundError

func (response GetCurrentTimer404JSONResponse) VisitGetCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentTimer500JSONResponse InternalServerError

func (response GetCurrentTimer500JSONResponse) VisitGetCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PauseCurrentTimerRequestObject struct {
}

type PauseCurrentTimerResponseObject interface {
	VisitPauseCurrentTimerResponse(w http.ResponseWriter) error
}

type PauseCurrentTimer200JSONResponse TimerAction

func (response PauseCurrentTimer200JSONResponse) VisitPauseCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PauseCurrentTimer401JSONResponse NotAuthorizedError

func (response PauseCurrentTimer401JSONResponse) VisitPauseCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PauseCurrentTimer404JSONResponse NotFoundError

func (response PauseCurrentTimer404JSONResponse) VisitPauseCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PauseCurrentTimer409JSONResponse ConflictError

func (response PauseCurrentTimer409JSONResponse) VisitPauseCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PauseCurrentTimer500JSONResponse InternalServerError

func (response PauseCurrentTimer500JSONResponse) VisitPauseCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type StartCurrentTimerRequestObject struct {
}

type StartCurrentTimerResponseObject interface {
	VisitStartCurrentTimerResponse(w http.ResponseWriter) error
}

type StartCurrentTimer200JSONResponse TimerAction

func (response StartCurrentTimer200JSONResponse) VisitStartCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartCurrentTimer401JSONResponse NotAuthorizedError

func (response StartCurrentTimer401JSONResponse) VisitStartCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StartCurrentTimer404JSONResponse NotFoundError

func (response StartCurrentTimer404JSONResponse) VisitStartCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StartCurrentTimer409JSONResponse ConflictError

func (response StartCurrentTimer409JSONResponse) VisitStartCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type StartCurrentTimer500JSONResponse InternalServerError

func (response StartCurrentTimer500JSONResponse) VisitStartCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Log in an existing user
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Log out the current user
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Register a new user account
	// (POST /auth/signup)
	SignUp(ctx context.Context, request SignUpRequestObject) (SignUpResponseObject, error)
	// Get a list of effects available for rolling
	// (POST /effects/available)
	GetAvailableEffects(ctx context.Context, request GetAvailableEffectsRequestObject) (GetAvailableEffectsResponseObject, error)
	// Check if there are any effect rolls available
	// (GET /effects/has-roll)
	CheckAvailableEffectRoll(ctx context.Context, request CheckAvailableEffectRollRequestObject) (CheckAvailableEffectRollResponseObject, error)
	// Get a list of all effect rolls
	// (GET /effects/history)
	GetEffectHistory(ctx context.Context, request GetEffectHistoryRequestObject) (GetEffectHistoryResponseObject, error)
	// Make the roll of the effect available
	// (POST /effects/roll)
	MakeEffectRoll(ctx context.Context, request MakeEffectRollRequestObject) (MakeEffectRollResponseObject, error)
	// Get the current game
	// (GET /games/current)
	GetCurrentGame(ctx context.Context, request GetCurrentGameRequestObject) (GetCurrentGameResponseObject, error)
	// Cancel the current game
	// (POST /games/current/cancel)
	CancelCurrentGame(ctx context.Context, request CancelCurrentGameRequestObject) (CancelCurrentGameResponseObject, error)
	// Complete the current game
	// (POST /games/current/finish)
	FinishCurrentGame(ctx context.Context, request FinishCurrentGameRequestObject) (FinishCurrentGameResponseObject, error)
	// Get a list of all games played
	// (GET /games/history)
	GetGameHistory(ctx context.Context, request GetGameHistoryRequestObject) (GetGameHistoryResponseObject, error)
	// Select a random game from the wishlist
	// (POST /games/roll)
	MakeGameRoll(ctx context.Context, request MakeGameRollRequestObject) (MakeGameRollResponseObject, error)
	// Get game wishlist
	// (GET /games/unplayed)
	GetUnplayedGames(ctx context.Context, request GetUnplayedGamesRequestObject) (GetUnplayedGamesResponseObject, error)
	// Add game wishlist
	// (POST /games/unplayed)
	AddUnplayedGames(ctx context.Context, request AddUnplayedGamesRequestObject) (AddUnplayedGamesResponseObject, error)
	// Get a timer for the current game
	// (GET /timers/current)
	GetCurrentTimer(ctx context.Context, request GetCurrentTimerRequestObject) (GetCurrentTimerResponseObject, error)
	// Pause the current timer
	// (POST /timers/current/pause)
	PauseCurrentTimer(ctx context.Context, request PauseCurrentTimerRequestObject) (PauseCurrentTimerResponseObject, error)
	// Start or continue the current timer
	// (POST /timers/current/start)
	StartCurrentTimer(ctx context.Context, request StartCurrentTimerRequestObject) (StartCurrentTimerResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx echo.Context) error {
	var request LogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SignUp operation middleware
func (sh *strictHandler) SignUp(ctx echo.Context) error {
	var request SignUpRequestObject

	var body SignUpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SignUp(ctx.Request().Context(), request.(SignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SignUpResponseObject); ok {
		return validResponse.VisitSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAvailableEffects operation middleware
func (sh *strictHandler) GetAvailableEffects(ctx echo.Context) error {
	var request GetAvailableEffectsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAvailableEffects(ctx.Request().Context(), request.(GetAvailableEffectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAvailableEffects")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAvailableEffectsResponseObject); ok {
		return validResponse.VisitGetAvailableEffectsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CheckAvailableEffectRoll operation middleware
func (sh *strictHandler) CheckAvailableEffectRoll(ctx echo.Context) error {
	var request CheckAvailableEffectRollRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CheckAvailableEffectRoll(ctx.Request().Context(), request.(CheckAvailableEffectRollRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckAvailableEffectRoll")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CheckAvailableEffectRollResponseObject); ok {
		return validResponse.VisitCheckAvailableEffectRollResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetEffectHistory operation middleware
func (sh *strictHandler) GetEffectHistory(ctx echo.Context) error {
	var request GetEffectHistoryRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetEffectHistory(ctx.Request().Context(), request.(GetEffectHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEffectHistory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetEffectHistoryResponseObject); ok {
		return validResponse.VisitGetEffectHistoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// MakeEffectRoll operation middleware
func (sh *strictHandler) MakeEffectRoll(ctx echo.Context) error {
	var request MakeEffectRollRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.MakeEffectRoll(ctx.Request().Context(), request.(MakeEffectRollRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MakeEffectRoll")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(MakeEffectRollResponseObject); ok {
		return validResponse.VisitMakeEffectRollResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentGame operation middleware
func (sh *strictHandler) GetCurrentGame(ctx echo.Context) error {
	var request GetCurrentGameRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentGame(ctx.Request().Context(), request.(GetCurrentGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCurrentGameResponseObject); ok {
		return validResponse.VisitGetCurrentGameResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CancelCurrentGame operation middleware
func (sh *strictHandler) CancelCurrentGame(ctx echo.Context) error {
	var request CancelCurrentGameRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CancelCurrentGame(ctx.Request().Context(), request.(CancelCurrentGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelCurrentGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CancelCurrentGameResponseObject); ok {
		return validResponse.VisitCancelCurrentGameResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// FinishCurrentGame operation middleware
func (sh *strictHandler) FinishCurrentGame(ctx echo.Context) error {
	var request FinishCurrentGameRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.FinishCurrentGame(ctx.Request().Context(), request.(FinishCurrentGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FinishCurrentGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(FinishCurrentGameResponseObject); ok {
		return validResponse.VisitFinishCurrentGameResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetGameHistory operation middleware
func (sh *strictHandler) GetGameHistory(ctx echo.Context) error {
	var request GetGameHistoryRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetGameHistory(ctx.Request().Context(), request.(GetGameHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGameHistory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetGameHistoryResponseObject); ok {
		return validResponse.VisitGetGameHistoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// MakeGameRoll operation middleware
func (sh *strictHandler) MakeGameRoll(ctx echo.Context) error {
	var request MakeGameRollRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.MakeGameRoll(ctx.Request().Context(), request.(MakeGameRollRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MakeGameRoll")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(MakeGameRollResponseObject); ok {
		return validResponse.VisitMakeGameRollResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUnplayedGames operation middleware
func (sh *strictHandler) GetUnplayedGames(ctx echo.Context) error {
	var request GetUnplayedGamesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUnplayedGames(ctx.Request().Context(), request.(GetUnplayedGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUnplayedGames")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUnplayedGamesResponseObject); ok {
		return validResponse.VisitGetUnplayedGamesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AddUnplayedGames operation middleware
func (sh *strictHandler) AddUnplayedGames(ctx echo.Context) error {
	var request AddUnplayedGamesRequestObject

	var body AddUnplayedGamesJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AddUnplayedGames(ctx.Request().Context(), request.(AddUnplayedGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddUnplayedGames")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AddUnplayedGamesResponseObject); ok {
		return validResponse.VisitAddUnplayedGamesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentTimer operation middleware
func (sh *strictHandler) GetCurrentTimer(ctx echo.Context) error {
	var request GetCurrentTimerRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentTimer(ctx.Request().Context(), request.(GetCurrentTimerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentTimer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCurrentTimerResponseObject); ok {
		return validResponse.VisitGetCurrentTimerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PauseCurrentTimer operation middleware
func (sh *strictHandler) PauseCurrentTimer(ctx echo.Context) error {
	var request PauseCurrentTimerRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PauseCurrentTimer(ctx.Request().Context(), request.(PauseCurrentTimerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PauseCurrentTimer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PauseCurrentTimerResponseObject); ok {
		return validResponse.VisitPauseCurrentTimerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// StartCurrentTimer operation middleware
func (sh *strictHandler) StartCurrentTimer(ctx echo.Context) error {
	var request StartCurrentTimerRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartCurrentTimer(ctx.Request().Context(), request.(StartCurrentTimerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartCurrentTimer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(StartCurrentTimerResponseObject); ok {
		return validResponse.VisitStartCurrentTimerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
