// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ConflictExceptionCode.
const (
	NOAVAILABLEROLLS    ConflictExceptionCode = "NO_AVAILABLE_ROLLS"
	TIMERINCORRECTSTATE ConflictExceptionCode = "TIMER_INCORRECT_STATE"
	USERALREADYEXISTS   ConflictExceptionCode = "USER_ALREADY_EXISTS"
)

// Defines values for DatabaseQueryExceptionCode.
const (
	DATABASEQUERY DatabaseQueryExceptionCode = "DATABASE_QUERY"
)

// Defines values for GameState.
const (
	GameStateFinished GameState = "finished"
	GameStateStarted  GameState = "started"
)

// Defines values for NotFoundExceptionCode.
const (
	GAMENOTFOUND  NotFoundExceptionCode = "GAME_NOT_FOUND"
	TIMERNOTFOUND NotFoundExceptionCode = "TIMER_NOT_FOUND"
	USERNOTFOUND  NotFoundExceptionCode = "USER_NOT_FOUND"
)

// Defines values for TimerState.
const (
	TimerStateCreated  TimerState = "created"
	TimerStateFinished TimerState = "finished"
	TimerStatePaused   TimerState = "paused"
	TimerStateRolled   TimerState = "rolled"
	TimerStateRunning  TimerState = "running"
)

// Defines values for TimerActionAction.
const (
	Pause TimerActionAction = "pause"
	Start TimerActionAction = "start"
	Stop  TimerActionAction = "stop"
)

// ConflictException defines model for ConflictException.
type ConflictException struct {
	Code    ConflictExceptionCode `json:"code"`
	Message string                `json:"message"`
}

// ConflictExceptionCode defines model for ConflictException.Code.
type ConflictExceptionCode string

// DatabaseQueryException defines model for DatabaseQueryException.
type DatabaseQueryException struct {
	Code    DatabaseQueryExceptionCode `json:"code"`
	Message string                     `json:"message"`
}

// DatabaseQueryExceptionCode defines model for DatabaseQueryException.Code.
type DatabaseQueryExceptionCode string

// Effect defines model for Effect.
type Effect struct {
	Description  string    `json:"description"`
	GameName     *Name     `json:"gameName,omitempty"`
	Name         Name      `json:"name"`
	ReceivedDate time.Time `json:"receivedDate"`
}

// Effects defines model for Effects.
type Effects = []Effect

// Exception defines model for Exception.
type Exception struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Game defines model for Game.
type Game struct {
	Id    Id         `json:"id"`
	Link  *string    `json:"link,omitempty"`
	Name  Name       `json:"name"`
	State *GameState `json:"state,omitempty"`
}

// GameState defines model for Game.State.
type GameState string

// Id defines model for Id.
type Id = openapi_types.UUID

// Name defines model for Name.
type Name = string

// NotFoundException defines model for NotFoundException.
type NotFoundException struct {
	Code    NotFoundExceptionCode `json:"code"`
	Message string                `json:"message"`
}

// NotFoundExceptionCode defines model for NotFoundException.Code.
type NotFoundExceptionCode string

// Timer defines model for Timer.
type Timer struct {
	DurationInS      int32      `json:"durationInS"`
	Id               Id         `json:"id"`
	RemainingTimeInS int32      `json:"remainingTimeInS"`
	State            TimerState `json:"state"`
}

// TimerState defines model for Timer.State.
type TimerState string

// TimerAction defines model for TimerAction.
type TimerAction struct {
	Action           TimerActionAction `json:"action"`
	RemainingTimeInS int32             `json:"remainingTimeInS"`
}

// TimerActionAction defines model for TimerAction.Action.
type TimerActionAction string

// UnplayedGame defines model for UnplayedGame.
type UnplayedGame struct {
	Link *string `json:"link,omitempty"`
	Name Name    `json:"name"`
}

// UnplayedGames defines model for UnplayedGames.
type UnplayedGames = []UnplayedGame

// User defines model for User.
type User struct {
	Id   Id   `json:"id"`
	Name Name `json:"name"`
}

// UserId defines model for UserId.
type UserId = Id

// UserName defines model for UserName.
type UserName = Name

// AddUnplayedGamesJSONRequestBody defines body for AddUnplayedGames for application/json ContentType.
type AddUnplayedGamesJSONRequestBody = UnplayedGames

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /users/{name})
	GetUser(ctx echo.Context, name UserName) error

	// (POST /users/{name})
	CreateUser(ctx echo.Context, name UserName) error

	// (GET /users/{userId}/effects/has-roll)
	CheckEffectRoll(ctx echo.Context, userId UserId) error

	// (GET /users/{userId}/effects/history)
	GetEffectHistory(ctx echo.Context, userId UserId) error

	// (POST /users/{userId}/effects/roll)
	MakeEffectRoll(ctx echo.Context, userId UserId) error

	// (GET /users/{userId}/games/current)
	GetCurrentGame(ctx echo.Context, userId UserId) error

	// (GET /users/{userId}/games/current/finish)
	FinishCurrentGame(ctx echo.Context, userId UserId) error

	// (GET /users/{userId}/games/roll)
	MakeGameRoll(ctx echo.Context, userId UserId) error

	// (GET /users/{userId}/games/unplayed)
	GetUnplayedGames(ctx echo.Context, userId UserId) error

	// (POST /users/{userId}/games/unplayed)
	AddUnplayedGames(ctx echo.Context, userId UserId) error

	// (GET /users/{userId}/timers/current)
	GetCurrentTimer(ctx echo.Context, userId UserId) error

	// (POST /users/{userId}/timers/current/pause)
	PauseCurrentTimer(ctx echo.Context, userId UserId) error

	// (POST /users/{userId}/timers/current/start)
	StartCurrentTimer(ctx echo.Context, userId UserId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name UserName

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUser(ctx, name)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name UserName

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUser(ctx, name)
	return err
}

// CheckEffectRoll converts echo context to params.
func (w *ServerInterfaceWrapper) CheckEffectRoll(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CheckEffectRoll(ctx, userId)
	return err
}

// GetEffectHistory converts echo context to params.
func (w *ServerInterfaceWrapper) GetEffectHistory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEffectHistory(ctx, userId)
	return err
}

// MakeEffectRoll converts echo context to params.
func (w *ServerInterfaceWrapper) MakeEffectRoll(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.MakeEffectRoll(ctx, userId)
	return err
}

// GetCurrentGame converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentGame(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentGame(ctx, userId)
	return err
}

// FinishCurrentGame converts echo context to params.
func (w *ServerInterfaceWrapper) FinishCurrentGame(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FinishCurrentGame(ctx, userId)
	return err
}

// MakeGameRoll converts echo context to params.
func (w *ServerInterfaceWrapper) MakeGameRoll(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.MakeGameRoll(ctx, userId)
	return err
}

// GetUnplayedGames converts echo context to params.
func (w *ServerInterfaceWrapper) GetUnplayedGames(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUnplayedGames(ctx, userId)
	return err
}

// AddUnplayedGames converts echo context to params.
func (w *ServerInterfaceWrapper) AddUnplayedGames(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddUnplayedGames(ctx, userId)
	return err
}

// GetCurrentTimer converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentTimer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentTimer(ctx, userId)
	return err
}

// PauseCurrentTimer converts echo context to params.
func (w *ServerInterfaceWrapper) PauseCurrentTimer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PauseCurrentTimer(ctx, userId)
	return err
}

// StartCurrentTimer converts echo context to params.
func (w *ServerInterfaceWrapper) StartCurrentTimer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StartCurrentTimer(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/users/:name", wrapper.GetUser)
	router.POST(baseURL+"/users/:name", wrapper.CreateUser)
	router.GET(baseURL+"/users/:userId/effects/has-roll", wrapper.CheckEffectRoll)
	router.GET(baseURL+"/users/:userId/effects/history", wrapper.GetEffectHistory)
	router.POST(baseURL+"/users/:userId/effects/roll", wrapper.MakeEffectRoll)
	router.GET(baseURL+"/users/:userId/games/current", wrapper.GetCurrentGame)
	router.GET(baseURL+"/users/:userId/games/current/finish", wrapper.FinishCurrentGame)
	router.GET(baseURL+"/users/:userId/games/roll", wrapper.MakeGameRoll)
	router.GET(baseURL+"/users/:userId/games/unplayed", wrapper.GetUnplayedGames)
	router.POST(baseURL+"/users/:userId/games/unplayed", wrapper.AddUnplayedGames)
	router.GET(baseURL+"/users/:userId/timers/current", wrapper.GetCurrentTimer)
	router.POST(baseURL+"/users/:userId/timers/current/pause", wrapper.PauseCurrentTimer)
	router.POST(baseURL+"/users/:userId/timers/current/start", wrapper.StartCurrentTimer)

}

type GetUserRequestObject struct {
	Name UserName `json:"name"`
}

type GetUserResponseObject interface {
	VisitGetUserResponse(w http.ResponseWriter) error
}

type GetUser200JSONResponse User

func (response GetUser200JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUser404JSONResponse NotFoundException

func (response GetUser404JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetUser503JSONResponse DatabaseQueryException

func (response GetUser503JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Name UserName `json:"name"`
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser200JSONResponse User

func (response CreateUser200JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser409JSONResponse ConflictException

func (response CreateUser409JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser503JSONResponse DatabaseQueryException

func (response CreateUser503JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type CheckEffectRollRequestObject struct {
	UserId UserId `json:"userId"`
}

type CheckEffectRollResponseObject interface {
	VisitCheckEffectRollResponse(w http.ResponseWriter) error
}

type CheckEffectRoll200JSONResponse bool

func (response CheckEffectRoll200JSONResponse) VisitCheckEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CheckEffectRoll404JSONResponse NotFoundException

func (response CheckEffectRoll404JSONResponse) VisitCheckEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CheckEffectRoll503JSONResponse DatabaseQueryException

func (response CheckEffectRoll503JSONResponse) VisitCheckEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetEffectHistoryRequestObject struct {
	UserId UserId `json:"userId"`
}

type GetEffectHistoryResponseObject interface {
	VisitGetEffectHistoryResponse(w http.ResponseWriter) error
}

type GetEffectHistory200JSONResponse Effects

func (response GetEffectHistory200JSONResponse) VisitGetEffectHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEffectHistory404JSONResponse NotFoundException

func (response GetEffectHistory404JSONResponse) VisitGetEffectHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetEffectHistory503JSONResponse DatabaseQueryException

func (response GetEffectHistory503JSONResponse) VisitGetEffectHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type MakeEffectRollRequestObject struct {
	UserId UserId `json:"userId"`
}

type MakeEffectRollResponseObject interface {
	VisitMakeEffectRollResponse(w http.ResponseWriter) error
}

type MakeEffectRoll200JSONResponse Effect

func (response MakeEffectRoll200JSONResponse) VisitMakeEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MakeEffectRoll404JSONResponse NotFoundException

func (response MakeEffectRoll404JSONResponse) VisitMakeEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MakeEffectRoll409JSONResponse ConflictException

func (response MakeEffectRoll409JSONResponse) VisitMakeEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type MakeEffectRoll503JSONResponse DatabaseQueryException

func (response MakeEffectRoll503JSONResponse) VisitMakeEffectRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentGameRequestObject struct {
	UserId UserId `json:"userId"`
}

type GetCurrentGameResponseObject interface {
	VisitGetCurrentGameResponse(w http.ResponseWriter) error
}

type GetCurrentGame200JSONResponse Game

func (response GetCurrentGame200JSONResponse) VisitGetCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentGame404JSONResponse NotFoundException

func (response GetCurrentGame404JSONResponse) VisitGetCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentGame503JSONResponse DatabaseQueryException

func (response GetCurrentGame503JSONResponse) VisitGetCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type FinishCurrentGameRequestObject struct {
	UserId UserId `json:"userId"`
}

type FinishCurrentGameResponseObject interface {
	VisitFinishCurrentGameResponse(w http.ResponseWriter) error
}

type FinishCurrentGame200Response struct {
}

func (response FinishCurrentGame200Response) VisitFinishCurrentGameResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type FinishCurrentGame404JSONResponse NotFoundException

func (response FinishCurrentGame404JSONResponse) VisitFinishCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type FinishCurrentGame503JSONResponse DatabaseQueryException

func (response FinishCurrentGame503JSONResponse) VisitFinishCurrentGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type MakeGameRollRequestObject struct {
	UserId UserId `json:"userId"`
}

type MakeGameRollResponseObject interface {
	VisitMakeGameRollResponse(w http.ResponseWriter) error
}

type MakeGameRoll200JSONResponse Game

func (response MakeGameRoll200JSONResponse) VisitMakeGameRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MakeGameRoll404JSONResponse NotFoundException

func (response MakeGameRoll404JSONResponse) VisitMakeGameRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MakeGameRoll409JSONResponse ConflictException

func (response MakeGameRoll409JSONResponse) VisitMakeGameRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type MakeGameRoll503JSONResponse DatabaseQueryException

func (response MakeGameRoll503JSONResponse) VisitMakeGameRollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetUnplayedGamesRequestObject struct {
	UserId UserId `json:"userId"`
}

type GetUnplayedGamesResponseObject interface {
	VisitGetUnplayedGamesResponse(w http.ResponseWriter) error
}

type GetUnplayedGames200JSONResponse UnplayedGames

func (response GetUnplayedGames200JSONResponse) VisitGetUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUnplayedGames404JSONResponse NotFoundException

func (response GetUnplayedGames404JSONResponse) VisitGetUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetUnplayedGames503JSONResponse DatabaseQueryException

func (response GetUnplayedGames503JSONResponse) VisitGetUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type AddUnplayedGamesRequestObject struct {
	UserId UserId `json:"userId"`
	Body   *AddUnplayedGamesJSONRequestBody
}

type AddUnplayedGamesResponseObject interface {
	VisitAddUnplayedGamesResponse(w http.ResponseWriter) error
}

type AddUnplayedGames200Response struct {
}

func (response AddUnplayedGames200Response) VisitAddUnplayedGamesResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type AddUnplayedGames404JSONResponse NotFoundException

func (response AddUnplayedGames404JSONResponse) VisitAddUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddUnplayedGames503JSONResponse DatabaseQueryException

func (response AddUnplayedGames503JSONResponse) VisitAddUnplayedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentTimerRequestObject struct {
	UserId UserId `json:"userId"`
}

type GetCurrentTimerResponseObject interface {
	VisitGetCurrentTimerResponse(w http.ResponseWriter) error
}

type GetCurrentTimer200JSONResponse Timer

func (response GetCurrentTimer200JSONResponse) VisitGetCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentTimer404JSONResponse NotFoundException

func (response GetCurrentTimer404JSONResponse) VisitGetCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentTimer503JSONResponse DatabaseQueryException

func (response GetCurrentTimer503JSONResponse) VisitGetCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type PauseCurrentTimerRequestObject struct {
	UserId UserId `json:"userId"`
}

type PauseCurrentTimerResponseObject interface {
	VisitPauseCurrentTimerResponse(w http.ResponseWriter) error
}

type PauseCurrentTimer200JSONResponse TimerAction

func (response PauseCurrentTimer200JSONResponse) VisitPauseCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PauseCurrentTimer404JSONResponse NotFoundException

func (response PauseCurrentTimer404JSONResponse) VisitPauseCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PauseCurrentTimer409JSONResponse ConflictException

func (response PauseCurrentTimer409JSONResponse) VisitPauseCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PauseCurrentTimer503JSONResponse DatabaseQueryException

func (response PauseCurrentTimer503JSONResponse) VisitPauseCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type StartCurrentTimerRequestObject struct {
	UserId UserId `json:"userId"`
}

type StartCurrentTimerResponseObject interface {
	VisitStartCurrentTimerResponse(w http.ResponseWriter) error
}

type StartCurrentTimer200JSONResponse TimerAction

func (response StartCurrentTimer200JSONResponse) VisitStartCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartCurrentTimer404JSONResponse NotFoundException

func (response StartCurrentTimer404JSONResponse) VisitStartCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StartCurrentTimer409JSONResponse ConflictException

func (response StartCurrentTimer409JSONResponse) VisitStartCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type StartCurrentTimer503JSONResponse DatabaseQueryException

func (response StartCurrentTimer503JSONResponse) VisitStartCurrentTimerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /users/{name})
	GetUser(ctx context.Context, request GetUserRequestObject) (GetUserResponseObject, error)

	// (POST /users/{name})
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)

	// (GET /users/{userId}/effects/has-roll)
	CheckEffectRoll(ctx context.Context, request CheckEffectRollRequestObject) (CheckEffectRollResponseObject, error)

	// (GET /users/{userId}/effects/history)
	GetEffectHistory(ctx context.Context, request GetEffectHistoryRequestObject) (GetEffectHistoryResponseObject, error)

	// (POST /users/{userId}/effects/roll)
	MakeEffectRoll(ctx context.Context, request MakeEffectRollRequestObject) (MakeEffectRollResponseObject, error)

	// (GET /users/{userId}/games/current)
	GetCurrentGame(ctx context.Context, request GetCurrentGameRequestObject) (GetCurrentGameResponseObject, error)

	// (GET /users/{userId}/games/current/finish)
	FinishCurrentGame(ctx context.Context, request FinishCurrentGameRequestObject) (FinishCurrentGameResponseObject, error)

	// (GET /users/{userId}/games/roll)
	MakeGameRoll(ctx context.Context, request MakeGameRollRequestObject) (MakeGameRollResponseObject, error)

	// (GET /users/{userId}/games/unplayed)
	GetUnplayedGames(ctx context.Context, request GetUnplayedGamesRequestObject) (GetUnplayedGamesResponseObject, error)

	// (POST /users/{userId}/games/unplayed)
	AddUnplayedGames(ctx context.Context, request AddUnplayedGamesRequestObject) (AddUnplayedGamesResponseObject, error)

	// (GET /users/{userId}/timers/current)
	GetCurrentTimer(ctx context.Context, request GetCurrentTimerRequestObject) (GetCurrentTimerResponseObject, error)

	// (POST /users/{userId}/timers/current/pause)
	PauseCurrentTimer(ctx context.Context, request PauseCurrentTimerRequestObject) (PauseCurrentTimerResponseObject, error)

	// (POST /users/{userId}/timers/current/start)
	StartCurrentTimer(ctx context.Context, request StartCurrentTimerRequestObject) (StartCurrentTimerResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetUser operation middleware
func (sh *strictHandler) GetUser(ctx echo.Context, name UserName) error {
	var request GetUserRequestObject

	request.Name = name

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUser(ctx.Request().Context(), request.(GetUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserResponseObject); ok {
		return validResponse.VisitGetUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(ctx echo.Context, name UserName) error {
	var request CreateUserRequestObject

	request.Name = name

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx.Request().Context(), request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		return validResponse.VisitCreateUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CheckEffectRoll operation middleware
func (sh *strictHandler) CheckEffectRoll(ctx echo.Context, userId UserId) error {
	var request CheckEffectRollRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CheckEffectRoll(ctx.Request().Context(), request.(CheckEffectRollRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckEffectRoll")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CheckEffectRollResponseObject); ok {
		return validResponse.VisitCheckEffectRollResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetEffectHistory operation middleware
func (sh *strictHandler) GetEffectHistory(ctx echo.Context, userId UserId) error {
	var request GetEffectHistoryRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetEffectHistory(ctx.Request().Context(), request.(GetEffectHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEffectHistory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetEffectHistoryResponseObject); ok {
		return validResponse.VisitGetEffectHistoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// MakeEffectRoll operation middleware
func (sh *strictHandler) MakeEffectRoll(ctx echo.Context, userId UserId) error {
	var request MakeEffectRollRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.MakeEffectRoll(ctx.Request().Context(), request.(MakeEffectRollRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MakeEffectRoll")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(MakeEffectRollResponseObject); ok {
		return validResponse.VisitMakeEffectRollResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentGame operation middleware
func (sh *strictHandler) GetCurrentGame(ctx echo.Context, userId UserId) error {
	var request GetCurrentGameRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentGame(ctx.Request().Context(), request.(GetCurrentGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCurrentGameResponseObject); ok {
		return validResponse.VisitGetCurrentGameResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// FinishCurrentGame operation middleware
func (sh *strictHandler) FinishCurrentGame(ctx echo.Context, userId UserId) error {
	var request FinishCurrentGameRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.FinishCurrentGame(ctx.Request().Context(), request.(FinishCurrentGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FinishCurrentGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(FinishCurrentGameResponseObject); ok {
		return validResponse.VisitFinishCurrentGameResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// MakeGameRoll operation middleware
func (sh *strictHandler) MakeGameRoll(ctx echo.Context, userId UserId) error {
	var request MakeGameRollRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.MakeGameRoll(ctx.Request().Context(), request.(MakeGameRollRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MakeGameRoll")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(MakeGameRollResponseObject); ok {
		return validResponse.VisitMakeGameRollResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUnplayedGames operation middleware
func (sh *strictHandler) GetUnplayedGames(ctx echo.Context, userId UserId) error {
	var request GetUnplayedGamesRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUnplayedGames(ctx.Request().Context(), request.(GetUnplayedGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUnplayedGames")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUnplayedGamesResponseObject); ok {
		return validResponse.VisitGetUnplayedGamesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AddUnplayedGames operation middleware
func (sh *strictHandler) AddUnplayedGames(ctx echo.Context, userId UserId) error {
	var request AddUnplayedGamesRequestObject

	request.UserId = userId

	var body AddUnplayedGamesJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AddUnplayedGames(ctx.Request().Context(), request.(AddUnplayedGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddUnplayedGames")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AddUnplayedGamesResponseObject); ok {
		return validResponse.VisitAddUnplayedGamesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentTimer operation middleware
func (sh *strictHandler) GetCurrentTimer(ctx echo.Context, userId UserId) error {
	var request GetCurrentTimerRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentTimer(ctx.Request().Context(), request.(GetCurrentTimerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentTimer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCurrentTimerResponseObject); ok {
		return validResponse.VisitGetCurrentTimerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PauseCurrentTimer operation middleware
func (sh *strictHandler) PauseCurrentTimer(ctx echo.Context, userId UserId) error {
	var request PauseCurrentTimerRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PauseCurrentTimer(ctx.Request().Context(), request.(PauseCurrentTimerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PauseCurrentTimer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PauseCurrentTimerResponseObject); ok {
		return validResponse.VisitPauseCurrentTimerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// StartCurrentTimer operation middleware
func (sh *strictHandler) StartCurrentTimer(ctx echo.Context, userId UserId) error {
	var request StartCurrentTimerRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartCurrentTimer(ctx.Request().Context(), request.(StartCurrentTimerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartCurrentTimer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(StartCurrentTimerResponseObject); ok {
		return validResponse.VisitStartCurrentTimerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
