// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// User defines model for User.
type User struct {
	Id   UserId   `json:"id"`
	Name Username `json:"name"`
}

// UserId defines model for UserId.
type UserId = int64

// Username defines model for Username.
type Username = string

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /users/{name})
	GetUsersName(ctx echo.Context, name Username) error

	// (POST /users/{name})
	PostUsersName(ctx echo.Context, name Username) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetUsersName converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersName(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name Username

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersName(ctx, name)
	return err
}

// PostUsersName converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersName(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name Username

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersName(ctx, name)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/users/:name", wrapper.GetUsersName)
	router.POST(baseURL+"/users/:name", wrapper.PostUsersName)

}

type GetUsersNameRequestObject struct {
	Name Username `json:"name"`
}

type GetUsersNameResponseObject interface {
	VisitGetUsersNameResponse(w http.ResponseWriter) error
}

type GetUsersName200JSONResponse User

func (response GetUsersName200JSONResponse) VisitGetUsersNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersName404Response struct {
}

func (response GetUsersName404Response) VisitGetUsersNameResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostUsersNameRequestObject struct {
	Name Username `json:"name"`
}

type PostUsersNameResponseObject interface {
	VisitPostUsersNameResponse(w http.ResponseWriter) error
}

type PostUsersName200Response struct {
}

func (response PostUsersName200Response) VisitPostUsersNameResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostUsersName409Response struct {
}

func (response PostUsersName409Response) VisitPostUsersNameResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /users/{name})
	GetUsersName(ctx context.Context, request GetUsersNameRequestObject) (GetUsersNameResponseObject, error)

	// (POST /users/{name})
	PostUsersName(ctx context.Context, request PostUsersNameRequestObject) (PostUsersNameResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetUsersName operation middleware
func (sh *strictHandler) GetUsersName(ctx echo.Context, name Username) error {
	var request GetUsersNameRequestObject

	request.Name = name

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersName(ctx.Request().Context(), request.(GetUsersNameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersName")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUsersNameResponseObject); ok {
		return validResponse.VisitGetUsersNameResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUsersName operation middleware
func (sh *strictHandler) PostUsersName(ctx echo.Context, name Username) error {
	var request PostUsersNameRequestObject

	request.Name = name

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersName(ctx.Request().Context(), request.(PostUsersNameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersName")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUsersNameResponseObject); ok {
		return validResponse.VisitPostUsersNameResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
